### ISSUE TITLE
Deployment the strapi CMS to digitalOcean

### ISSUE THREAD

**Issue by ab7z** [womenGoingBeyond/cms#9]
# Technical Story

CMS is deployed on DigitalOcean so stakeholders can access and try it out.

## Tasks

- [x] previous WP Droplet is deleted
- [x] a new Droplet for Strai is created
- [x] Strapi deployed on DigitalOcean
- [x] CI/CD through connection between GitHub and DigitalOcean 

## Log

- strapi requires more than 1G of RAM form admin interface
- Singapore is the nearest datacenter region to Cambodia
